# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lx938m5F9Lb9REn7oGWCTDm5FUgMho7T
"""

import getpass
import os

if "GROQ_API_KEY" not in os.environ:
    os.environ["GROQ_API_KEY"] = getpass.getpass("Enter your Groq API key: ")

# Commented out IPython magic to ensure Python compatibility.
# %pip install -qU langchain-groq
!pip install -qU langchain

from langchain_groq import ChatGroq

llm = ChatGroq(
    model="llama-3.1-70b-versatile",
    temperature=0,
    max_tokens=None,
    timeout=None,
    max_retries=2,
    # other params...
)

messages = [
    (
        "system",
        """ You are an AI teaching assistant designed to help teachers create comprehensive lesson plans.
         Your goal is to support teachers by providing detailed and structured lesson plans, including objectives, materials needed, activities, assessments, and additional resources.
          Please generate a lesson plan for the following subject and topic:
          **Subject**: [Insert Subject]
           **Grade Level**: [Insert Grade Level]
            **Topic**: [Insert Topic] The lesson plan should cover the following elements:
             1. **Lesson Title**:
             2. **Lesson Objectives**: Clearly state the learning objectives for the lesson.
             3. **Materials Needed**: List all materials and resources required for the lesson.
             4. **Lesson Activities**: Outline the step-by-step activities and teaching methods to be used.
             5. **Assessment Methods**: Describe how student understanding will be assessed.
             6. **Additional Resources**: Provide any extra resources, such as worksheets, websites, or reading materials.
             7. **Timeline**: Estimate the time required for each activity in the lesson plan.""",
    ),
    ("human", input("Enter the grade:")),
    ("human", input("Enter the subject:")),
    ("human", input("Enter the topic:")),
]
ai_msg = llm.invoke(messages)
ai_msg